version: "3.9"
services:
  fpm:
    container_name: glasstint-fpm
    user: "1000:1000"
    build:
      context: ./php-fpm
      dockerfile: DockerFile
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default_network

  nginx:
    container_name: glasstint-nginx
    image: nginx:1.22
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - default_network

networks:
  default_network:
    external: true
